name: Request a New Ontology Term
description: Request a new term to be added to the Mondo ontology.
title: Request for new term [NAME]
labels: [new term request]
assignees: nicolevasilevsky
body:
  - type: markdown
    attributes:
      value: |
        Use this form to request a new ontology term be added to Mondo. See additional guidance here: https://mondo.readthedocs.io/en/latest/editors-guide/c-make-good-term-request/.
  - type: input
    id: title
    attributes:
      label: Title
      description: What is the full title of your ontology? Please do not include redundant acronyms.
      placeholder: ex. Chemical Entities of Biological Interest
    validations:
      required: true

