name: Add synonym
description: Request a new term to be added to the Mondo ontology.
title: Request for new term [ADD NAME HERE]
labels: [ New term request ]
assignees: nicolevasilevsky
body:
  - type: markdown
    attributes:
      value: |
        Use this form to request a new ontology term be added to Mondo. See additional guidance here: https://mondo.readthedocs.io/en/latest/editors-guide/c-make-good-term-request/.
  - type: input
    id: Label
    attributes:
      label: Label
      description: Preferred term label. Please add the label in lowercase, unless it is a proper name.
      placeholder: ex. spindle cell rhabdomyosarcoma
    validations:
      required: true
