name: Add term- Request a New Ontology Term
description: Request a new term to be added to the Mondo ontology.
title: Request for new term [ADD NAME HERE]
labels: [ New term request ]
assignees: nicolevasilevsky
body:
  - type: markdown
    attributes:
      value: |
        Use this form to request a synonym be added to an existing Mondo term.
 - type: input
    id: term
    attributes:
      label: Mondo term
      description: Mondo term to which a synonym should be added.
      placeholder: ex. spindle cell rhabdomyosarcoma
    validations:
      required: true
