name: Add synonym
description: Request a new synonym to be added an existing Mondo term.
title: Request for new synonym [ADD NAME HERE]
labels: [ synonym ]
assignees: nicolevasilevsky
body:
  - type: markdown
    attributes:
      value: |
        Use this form to request a synonym be added to an existing Mondo term.
  - type: input
    id: Label
    attributes:
      label: Mondo term
      description: Mondo term to which a synonym should be added.
      placeholder: ex. spindle cell rhabdomyosarcoma
    validations:
      required: true
