name: Add synonym
description: Request a new synonym to be added an existing Mondo term.
title: Request for new synonym [ADD NAME HERE]
labels: [ synonym ]
assignees: nicolevasilevsky
body:
  - type: markdown
    attributes:
      value: |
        Use this form to request a synonym be added to an existing Mondo term.
  - type: input
    id: Label
    attributes:
      label: Label
      description: Preferred term label. Please add the label in lowercase, unless it is a proper name.
      placeholder: ex. spindle cell rhabdomyosarcoma
    validations:
      required: true
