# options: [min(15),dir(tmp),trim(true),max_and_cardinality(4),base('http://purl.obolibrary.org/obo/mondo'),exclude_prefixes(['UBERON']),load_import_closure(false),annotations([ann(exact_synonym,oio:hasExactSynonym,0.05),ann(related_synonym,oio:hasRelatedSynonym,0.05)])]
pattern_name: disease realized in response to environmental exposure
pattern_iri: http://purl.obolibrary.org/obo/mondo/patterns/realized_in_response_to_evironmental_exposure.yaml

description: >-
    This pattern is used for a disease, where the cause of the disease is an exposure to an environmental stimulus (using ECTO exposure terms).

    Examples: [chemically-induced disorder](http://purl.obolibrary.org/obo/MONDO_0029001),
    [alcohol amnestic disorder](http://purl.obolibrary.org/obo/MONDO_0021702), [alcoholic
    polyneuropathy](http://purl.obolibrary.org/obo/MONDO_0006645) (26 total)

classes:
    disease: MONDO:0000001
    exposure event: ExO:0000002
   
relations:
    realized in response to: RO:0009501

vars:
    disease: "'disease'"
    exposure: "'exposure event'"

name:
    text: '%s realized in response to %s'
    vars:
      - disease
      - exposure

def:
  # Could not induce def, using default
    text: Any %s that is realized in response to a %s
    vars:
      - disease
      - exposure

annotationProperties:
    exact_synonym: oio:hasExactSynonym
    related_synonym: oio:hasRelatedSynonym

# could not infer annotations


equivalentTo:
    text: "%s and ('realized in response to' some %s)"
    vars:
      - disease
      - exposure

contributors:
  - https://orcid.org/0000-0002-6601-2165
  - https://orcid.org/0000-0001-5208-3432
