name: Create ongoing diffs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  diff:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.2.29
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Run diff
        run: cd src/ontology/ && make IMP=false PAT=false MIR=false all_release_reports
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
