name: Update Mappings

on:
  schedule:
    - cron: '0 14 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.4
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Set env variables.
        id: vars
        run: |
          echo "resource=src/ontology/mondo-edit.obo" >> $GITHUB_ENV
          echo "branch-name=mapping_automation" >> $GITHUB_ENV
      - name: Run MakeFile
        id: MakeFile
        run: |
          cd src/ontology
          make GITHUB_ACTION=true IMP=false PAT=false update-doid-mappings -B
          make GITHUB_ACTION=true IMP=false PAT=false update-icd-mappings -B
          make GITHUB_ACTION=true IMP=false PAT=false update-ncit-mappings -B
          make GITHUB_ACTION=true IMP=false PAT=false update-omim-mappings -B
          make GITHUB_ACTION=true IMP=false PAT=false update-ordo-mappings -B
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update mappings in Mondo
          title: 'Update mappings in Mondo'
          body: |
            Update mappings in Mondo from external sources
          assignees: "sabrinatoro"
