name: Create new pull request

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: obolibrary/odkfull:v1.3.0
    strategy:
      matrix:
        python-version: ["3.9"]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set env variables.
        id: vars
        run: |
          echo "resource=src/ontology/mondo-edit.obo" >> $GITHUB_ENV
          echo "branch-name=make_automation_"${{ steps.gh-script-issue.outputs.result }} >> $GITHUB_ENV
          echo "PR_TITLE=Weekly automated mappings update." >> $GITHUB_ENV
          echo "PR_BODY=PLACEHOLDER: Needs to be updated." >> $GITHUB_ENV

      - name: Run MakeFile
        id: MakeFile
        run: |
          cd src/ontology
          make GITHUB_ACTION=true IMP=false PAT=false update-doid-mappings -B
          make GITHUB_ACTION=true IMP=false PAT=false update-icd-mappings -B
          make GITHUB_ACTION=true IMP=false PAT=false update-ncit-mappings -B
          make GITHUB_ACTION=true IMP=false PAT=false update-omim-mappings -B
          make GITHUB_ACTION=true IMP=false PAT=false update-ordo-mappings -B
          

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        if: ${{ env.PR_TITLE}}
        with:
          branch-suffix: short-commit-hash
          labels: Automated
          body: ${{ env.PR_BODY }}
          title: ${{ env.PR_TITLE }}
          base: ${{ github.head_ref }}
          branch: ${{ env.branch-name }}
          token: ${{ secrets.GH_TOKEN }}